name: Deploy workflow
on: 
 pull_request:
   types: opened
   branches:
     - main
     - 'dev-*' # dev-test1, dev-test2
     - 'feat/**' # feat/test1 , feat/test2/test3
 workflow_dispatch: 
 push:
   branches:
     - main
   paths-ignore: 
     - 'controllers/*'
jobs:
 test:
  runs-on: macos-14
  steps:
   - name: get code 
     uses: actions/checkout@v3
   - name: install node
     uses: actions/setup-node@v3
     with: 
       node_version: 18
   - name: install dependency 
     run: npm install
   - name: run tests
     run: npm test
 deploy:
  needs: test
  runs-on: macos-14
  steps:
    - name: get code
      uses: actions/checkout@v3
    - name: install dependency
      run: npm install
    - name: build code
      run: npm run build
    - name: deployment
      run: echo " deployment ..."
    
