name: Deploy workflow
on: 
 #pull_request:
  # types: opened
   #branches:
    # - main
     #- 'dev-*' # dev-test1, dev-test2
     # 'feat/**' # feat/test1 , feat/test2/test3
# workflow_dispatch: 
 push:
   branches:
     - main
   #paths-ignore: 
     #- 'controllers/*'
jobs:
 test:
  runs-on: macos-14
  steps:
   - name: get code 
     uses: actions/checkout@v3
   - name: cache dependencies
     uses: actions/cache@v3
     with:
       path: ~/.npm
       key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
   - name: install node
     uses: actions/setup-node@v3
     with: 
       node_version: 18
   - name: install dependency 
     run: npm install
   - name: run tests
     run: npm test
 build:
  needs: test
  runs-on: macos-14
  outputs:
    script-file: ${{steps.publish.outputs.script-file}}
  steps:
    - name: get code
      uses: actions/checkout@v3
    - name: cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json')}} # when ever this file change it re cache
    - name: install dependency
      run: npm install
    - name: build code
      run: npm run build
    - name: output js file
      id: publish
      run: find dist/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';' 
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist
        # path: |
              # dist
              # package.json
 deploy:
   needs: build
   runs-on: macos-14
   steps:  
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist-files
    - name: output content
      run: ls
    - name: output file name
      run: echo ${{needs.build.outputs.script-file}}
    - name: deployment
      run: echo " deployment ..."
    
